
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Id = 3F,
    Name = @"SLN20210114-202101142030_23342_PAKET1.prn.pdf",
    BusinessCaseId = @"254",
    Designation = @"Dividendengutschriften",
    Bank = @"NULL",
    Currency = @"NULL",
    Biller = @"NULL",
    RawText = @"raw text",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual UseCase with predicted UseCase from sample data...\n\n");


Console.WriteLine($"Id: {3F}");
Console.WriteLine($"Name: {@"SLN20210114-202101142030_23342_PAKET1.prn.pdf"}");
Console.WriteLine($"UseCase: {@"BSP-Beleg"}");
Console.WriteLine($"BusinessCaseId: {@"254"}");
Console.WriteLine($"Designation: {@"Dividendengutschriften"}");
Console.WriteLine($"Bank: {@"NULL"}");
Console.WriteLine($"Currency: {@"NULL"}");
Console.WriteLine($"Biller: {@"NULL"}");
Console.WriteLine($"RawText: {@"Raw text
On multiple lines"}");

Console.WriteLine($"\n\nPredicted UseCase: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

